services:
  - type: web
    name: gerenciador-de-livros
    runtime: docker
    repo: https://github.com/SenhorArroz/GerenciarIdeiasLivros.git
    plan: free
    region: oregon
    autoDeploy: true
    dockerCommand: "/usr/local/bin/start.sh"
    dockerContext: .
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://gerenciador-de-livros.onrender.com
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: livros-db
          property: connectionString
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false

databases:
  - name: livros-db
    databaseName: livros
    user: livrosdbuser
    plan: free
    region: oregon
    postgresMajorVersion: "14"
